### ISSUE TITLE
Sanctum + Proxy: Login works, but refreshing the page is logging out the user

### ISSUE THREAD

**Issue by ahoiroman** [Teranode/nuxt-module-alternatives#42]
Hello everybody,

I got a config like this:

```
    axios: {
        credentials: true,
        proxy: true
    },
    proxy: {
        '/backend': {
            target: process.env.NUXT_PUBLIC_APP_URL,
            changeOrigin: true,
            secure: false,
            rewrite: (path) => path.replace(/^\/backend/, ''),
            common: {
                'Accept': 'application/json, text/plain, */*'
            },
        },
    },
    auth: {
        globalMiddleware: true,
        // @ts-ignore
        redirect: {
            home: '/dashboard',
            logout: '/',
            login: '/auth/signin',
        },
        strategies: {
            // @ts-ignore
            api: {
                provider: 'laravel/sanctum',
                url: process.env.NUXT_PUBLIC_APP_URL,
                endpoints: {
                    csrf: {url: '/backend/sanctum/csrf-cookie'},
                    login: {url: '/backend/login'},
                    logout: {url: '/backend/logout'},
                    user: {url: '/backend/api/user'}
                },
            },
        }
    },
```

Now if I log in, everything works fine. But if I refresh the browser's page, I am getting this error:

```
[Vue warn]: Unhandled error during execution of setup function 
  at <Dashboard onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/dashboard" >
[nuxt] [request error] Cannot read properties of null (reading 'profile')
  at ./.nuxt/dist/server/server.mjs:41784:122  
  at Module.withAsyncContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7405:21)  
  at setup (./.nuxt/dist/server/server.mjs:41784:47)  
  at _sfc_main.setup (./.nuxt/dist/server/server.mjs:42345:23)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7027:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6982:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:316:17)
[nitro] Error while generating error response FetchError: 301  (/__nuxt_error?url=/dashboard&statusCode=500&statusMessage=Internal+Server+Error&message=Cannot+read+properties+of+null+(reading+'profile')&description=%3Cpre%3E%3Cspan+class=%22stack%22%3Eat+./.nuxt/dist/server/server.mjs:41784:122%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+Module.withAsyncContext+(./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7405:21)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+setup+(./.nuxt/dist/server/server.mjs:41784:47)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+_sfc_main.setup+(./.nuxt/dist/server/server.mjs:42345:23)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+callWithErrorHandling+(./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+setupStatefulComponent+(./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7027:29)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+setupComponent+(./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6982:11)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+renderComponentVNode+(./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+renderVNode+(./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+renderVNode+(./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:316:17)%3C/span%3E%3C/pre%3E&data)
    at async Object.errorhandler [as onError] (file:///Users/ahoi/Entwicklung/nuxtjs/example-website/.nuxt/dev/index.mjs:338:16)
    at async Server.nodeHandler (file:///Users/ahoi/Entwicklung/nuxtjs/example-website/node_modules/h3/dist/index.mjs:370:9)
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:377:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at Object.errorhandler [as onError] (file:///Users/ahoi/Entwicklung/nuxtjs/example-website/.nuxt/dev/index.mjs:342:13)
    at async Server.nodeHandler (file:///Users/ahoi/Entwicklung/nuxtjs/example-website/node_modules/h3/dist/index.mjs:370:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by ahoiroman** [comment]
This is the axios-debug-output:


```
[Axios] Response error: AxiosError: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
  port: 3000,
  address: '::1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -61,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'cache-control': 'max-age=0',
      'accept-encoding': 'gzip, deflate',
      referer: 'web.example.test',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15',
      'upgrade-insecure-requests': '1',
      cookie: 'auth.strategy=api; auth.redirect=%2Fdashboard; XSRF-TOKEN=eyJpdiI6ImFPU1lMRDZyanZMZm5NTGZpRm9hUUE9PSIsInZhbHVlIjoiUzkyMjl6ZDVjOFZNTWxGV3gxU0s4ckhrdkFES0w5YzFFRUdqbFNLQnJiSlJVSldMZTRPaEYwclgxRUNhLzdPSnFrb3hsc29kQjl2VktrSk1zTVNhdit1VDRIVDhMbTF4cVJHTnU3SnBOcCtsczRyemgralcrTlZVWUtoY3AwOGkiLCJtYWMiOiIxZTJhMTk0Y2M1ZGM5NjExZGVlZmM5MTczNzkxOTUwZmMxZjFjZTdiNWNlZmY3NjAzYzA1Nzk2NjQ4OGJiYzYxIiwidGFnIjoiIn0%3D; example_session=eyJpdiI6Inp6RFZGVDdGekpZelQybzk0OWw4cGc9PSIsInZhbHVlIjoiN21BcmpJc2xNWFJDenJJU09SKzdlR1hFMmNqc21Pcm1tWnhQbXVWRFpsQW0xUEc0RXJidjd6L2pKVGxmbGgweVNrOU9yMFM1L3JoYjJSdlNTUnhZVFQrQlZ4Q3BsSG9uMmwyMWNBOEVSblRHTk56K0t2L050MERiTis2ZUNpTSsiLCJtYWMiOiIyMzdjMjcyZjk4Y2EyZjE1YTQzOTVhMjc0MDc0YTZjZDZlMTAzYzZmYTc2YzMzMmJiNTUyMTM5OThkMWIwYjJkIiwidGFnIjoiIn0%3D',
      'accept-language': 'de-DE,de;q=0.9',
      connection: 'upgrade',
      'x-nginx-proxy': 'true',
      'x-client-verify': 'SUCCESS',
      'x-forwarded-for': '127.0.0.1',
      'x-real-ip': '127.0.0.1',
      accept: 'application/json, text/plain, */*'
    },
    baseURL: 'http://localhost:3000/',
    url: '/backend/api/user',
    method: 'get',
    withCredentials: true,
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/backend/api/user',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '3000',
      nativeProtocols: [Object],
      pathname: '/backend/api/user'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /backend/api/user HTTP/1.1\r\n' +
        'accept: application/json, text/plain, */*\r\n' +
        'cache-control: max-age=0\r\n' +
        'accept-encoding: gzip, deflate\r\n' +
        'referer: web.example.test\r\n' +
        'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15\r\n' +
        'upgrade-insecure-requests: 1\r\n' +
        'cookie: auth.strategy=api; auth.redirect=%2Fdashboard; XSRF-TOKEN=eyJpdiI6ImFPU1lMRDZyanZMZm5NTGZpRm9hUUE9PSIsInZhbHVlIjoiUzkyMjl6ZDVjOFZNTWxGV3gxU0s4ckhrdkFES0w5YzFFRUdqbFNLQnJiSlJVSldMZTRPaEYwclgxRUNhLzdPSnFrb3hsc29kQjl2VktrSk1zTVNhdit1VDRIVDhMbTF4cVJHTnU3SnBOcCtsczRyemgralcrTlZVWUtoY3AwOGkiLCJtYWMiOiIxZTJhMTk0Y2M1ZGM5NjExZGVlZmM5MTczNzkxOTUwZmMxZjFjZTdiNWNlZmY3NjAzYzA1Nzk2NjQ4OGJiYzYxIiwidGFnIjoiIn0%3D; example_session=eyJpdiI6Inp6RFZGVDdGekpZelQybzk0OWw4cGc9PSIsInZhbHVlIjoiN21BcmpJc2xNWFJDenJJU09SKzdlR1hFMmNqc21Pcm1tWnhQbXVWRFpsQW0xUEc0RXJidjd6L2pKVGxmbGgweVNrOU9yMFM1L3JoYjJSdlNTUnhZVFQrQlZ4Q3BsSG9uMmwyMWNBOEVSblRHTk56K0t2L050MERiTis2ZUNpTSsiLCJtYWMiOiIyMzdjMjcyZjk4Y2EyZjE1YTQzOTVhMjc0MDc0YTZjZDZlMTAzYzZmYTc2YzMzMmJiNTUyMTM5OThkMWIwYjJkIiwidGFnIjoiIn0%3D\r\n' +
        'accept-language: de-DE,de;q=0.9\r\n' +
        'connection: upgrade\r\n' +
        'x-nginx-proxy: true\r\n' +
        'x-client-verify: SUCCESS\r\n' +
        'x-forwarded-for: 127.0.0.1\r\n' +
        'x-real-ip: 127.0.0.1\r\n' +
        'Host: localhost:3000\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/backend/api/user',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://localhost:3000/backend/api/user',
    [Symbol(kCapture)]: false
  }
}

```

**Comment by Teranode** [comment]
this looks unrelated to the auth module and more of outputting the data.
The cookie/laravel-sanctum provider offers a property for the client and server side of the application to specify the property for. Try to fiddle around with that if you need, if there's an error on the server side then it can't log you in.

before (auth module default):

```ts
user: {
    property: false
},
```

after (nuxt alternative module default):
```ts
user: {
    property: {
        client: false,
        server: false
    }
},
```

**Comment by ahoiroman** [comment]
Hm, I am not that familiar with node, so please could you explain why it's a problem on outputting the data? Is it because it states that:

```
Cannot read properties of null (reading 'profile')
```

? 

In this case: The `dashboard.vue` contains:

```
{{$auth.user.profile}}}
```

If I remove this, the error is gone - but `{{$auth.loggedIn}}` returns `false` after refreshing the browser.

**Comment by Teranode** [comment]
I am unable to reproduce the issue you are encountering.

Refer to the docs here for an example of the Laravel Sanctum config: https://github.com/Teranode/nuxt-module-alternatives/tree/master/@nuxtjs-alt/auth

If that still does not work for you here is an example of the config I am utilizing, other than that it is out of my scope:

```ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    srcDir: 'project/',
    css: [
        'assets/scss/index.scss'
    ],
    modules: [
        '@nuxtjs-alt/auth',
        '@nuxtjs-alt/axios',
        '@nuxtjs-alt/pinia',
    ],
    axios: {
        credentials: true,
    },
    proxy: {
        '/api': {
            target: process.env.BROWSER_BASE_URL, // Use in server
            rewrite: (path) => path.replace(/^\/api/, '/api'),
        },
        '/sanctum': {
            target: process.env.BROWSER_BASE_URL // Use in server
        }
    },
    auth: {
        globalMiddleware: false,
        redirect: {
            login: '/login',
            logout: '/',
            callback: '/login',
            home: '/'
        },
        strategies: {
            localStorage: false,
            laravelSanctum: {
                provider: 'laravel/sanctum',
                cookie: {
                    server: true,
                    name: 'token',
                },
                endpoints: {
                    csrf: { url: '/sanctum/csrf-cookie' },
                    login: { url: '/api/user/login' },
                    user: { url: '/api/user/me' },
                    logout: { url: '/api/user/logout' },
                },
                user: {
                    property: {
                        client: false,
                        server: false
                    },
                    autoFetch: true
                }
            },
        }
    },
    runtimeConfig: {
        public: {
            axios: {
                browserBaseURL: process.env.BROWSER_BASE_URL
            }
        },
    },
    hooks: {
        'components:dirs' (dirs) {
            dirs.push({
                path: '~/components'
            })
        }
    },
    components: {
        global: false
    },
    typescript: {
        strict: true
    }
})

**Comment by ahoiroman** [comment]
Alright, so I guess it's necessary to include a baseURL in the axios-section like this:

```
        baseURL: process.env.NUXT_PUBLIC_APP_URL,
```

Doing so, it's magically working.

Thanks again for your help :-)
