### ISSUE TITLE
In a store, how do you access $auth?

### ISSUE THREAD

**Issue by nathanchase** [Teranode/nuxt-module-alternatives#53]
I can get to `$auth` by way of `useNuxtApp()` in components and composables, but how would you access it in a [Pinia](https://github.com/vuejs/pinia) store?

In components, I usually just do:
```js
const nuxtApp = useNuxtApp();
const authUser = nuxtApp.$auth.user;
```
but in a `stores/store.ts`, useNuxtApp is not available, so I'm not quite sure how to get to the context?
```
[nuxt] [request error] nuxt instance unavailable
  at Module.useNuxtApp (./.nuxt/dist/server/server.mjs:520:13)
  at $id_C1ltjrBOrk (./.nuxt/dist/server/server.mjs:10547:39)
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:32909:3)
```

I notice too that this version of the auth module is auto-creating a Pinia store called `auth` with all of the data objects, but I don't know how to access the store itself - usually it would be with some sort of `const authStore = useAuthStore;`.

Reference: https://github.com/vuejs/pinia/pull/1433#issuecomment-1192495203

**Comment by nathanchase** [comment]
Migrated this to a discussion: https://github.com/Teranode/nuxt-module-alternatives/discussions/54
