### ISSUE TITLE
Auth: Server side does not work

### ISSUE THREAD

**Issue by Caceresenzo** [Teranode/nuxt-module-alternatives#58]
Hello

After a lot of debugging, I found out that an error has been silenced.
The Auth module does not load the user while on the server.

I managed to print the error while on the server side:
```
TypeError: this.scheme.$auth.ctx.beforeNuxtRender is not a function
  at ConfigurationDocument.request (/DIR/.nuxt/dist/server/server.mjs:5353:31)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async ConfigurationDocument.init (/DIR/.nuxt/dist/server/server.mjs:5399:5)
  at async OpenIDConnectScheme.mounted (/DIR/.nuxt/dist/server/server.mjs:6694:5)
  at async Auth.init (/DIR/.nuxt/dist/server/server.mjs:4688:7)
  at async /DIR/.nuxt/dist/server/server.mjs:4552:9
  at async Object.callAsync (/DIR/node_modules/unctx/dist/index.mjs:45:16)
  at async applyPlugin (/DIR/.nuxt/dist/server/server.mjs:516:23)
  at async Module.applyPlugins (/DIR/.nuxt/dist/server/server.mjs:526:5)
  at async createNuxtAppServer (/DIR/.nuxt/dist/server/server.mjs:46:7)
```
The lines are not right, but here is the piece of code:
https://github.com/Teranode/nuxt-module-alternatives/blob/b19bc7051beb69109fa18bd7a6acb9da5463a5d4/%40nuxtjs-alt/auth/src/runtime/inc/configuration-document.ts#L62-L71

If you comment this line of code (since its only to avoid fetching it while being on the client side), another problem happen:
```
Error: nuxt instance unavailable
  at Module.useNuxtApp (/DIR/.nuxt/dist/server/server.mjs:584:13)
  at Module.useRoute (/DIR/.nuxt/dist/server/server.mjs:1340:32)
  at OpenIDConnectScheme.#handleCallback (/DIR/.nuxt/dist/server/server.mjs:6743:41)
  at OpenIDConnectScheme.mounted (/DIR/.nuxt/dist/server/server.mjs:6700:50)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Auth.init (/DIR/.nuxt/dist/server/server.mjs:4688:7)
  at async /DIR/.nuxt/dist/server/server.mjs:4552:9
  at async Object.callAsync (/DIR/node_modules/unctx/dist/index.mjs:45:16)
  at async applyPlugin (/DIR/.nuxt/dist/server/server.mjs:516:23)
  at async Module.applyPlugins (/DIR/.nuxt/dist/server/server.mjs:526:5)
```
Which this time lies here:
https://github.com/Teranode/nuxt-module-alternatives/blob/b19bc7051beb69109fa18bd7a6acb9da5463a5d4/%40nuxtjs-alt/auth/src/runtime/schemes/openIDConnect.ts#L192-L193

Seems like the scheme's [`mounted()`](https://github.com/Teranode/nuxt-module-alternatives/blob/b19bc7051beb69109fa18bd7a6acb9da5463a5d4/%40nuxtjs-alt/auth/src/runtime/schemes/openIDConnect.ts#L122) function is called too soon?

What do you think? I already spend way too much time debugging this... And I think I am close to finally make it work!
Could we discuss it by a faster way like via email or discord?

**Comment by Caceresenzo** [comment]
i messed up on the pull requests. I only wanted to do one but github.dev wasn't allowing me to update the first pull request...

**Comment by Caceresenzo** [comment]
@Teranode is there a problem with the pull requests?
Is it because you wanted all into one?

**Comment by Teranode** [comment]
I had updated the npm package, I don't update this repository at the same time as npm.

**Comment by Caceresenzo** [comment]
I am not sure to understand, but thanks for accepting the code anyway :)

**Comment by Caceresenzo** [comment]
It's now working without a problem!
Thanks a lot for maintaining this library!
