### ISSUE TITLE
Auth V2 does not work: TypeError: undefined is not an object (evaluating 'this.http.interceptors')

### ISSUE THREAD

**Issue by ahoiroman** [Teranode/nuxt-module-alternatives#71]
Hi there,

I tried to migrate to auth v2 using this config:

```
import {defineNuxtConfig} from 'nuxt'

export default defineNuxtConfig({
    build: {
        transpile: ['@heroicons/vue', /echarts/, 'resize-detector', 'reflect-metadata', '@headlessui/vue'],
    },
    buildModules: ['@intlify/nuxt3', '@nuxtjs-alt/google-fonts', ],
    modules: [
        '@nuxtjs-alt/auth',
        '@nuxtjs-alt/axios',
        '@nuxt/content',
        '@nuxtjs/tailwindcss',
        '@pinia/nuxt',
    ],
    router: {
        middleware: ['auth']
    },
    axios: {
        credentials: true,
        proxy: true,
        baseURL: process.env.NUXT_PUBLIC_BASE_URL,
        debug: process.env.NODE_ENV && process.env.NODE_ENV === 'development',
    },
    proxy: {
        '/backend': {
            target: process.env.NUXT_PUBLIC_APP_URL,
            changeOrigin: true,
            secure: process.env.NODE_ENV && process.env.NODE_ENV === 'development',
            credentials: true,
            rewrite: (path) => path.replace(/^\/backend/, ''),
            common: {
                'Accept': 'application/json, text/plain, */*'
            },
        },
    },
    auth: {
        strategies: {
            laravelSanctum: {
                provider: 'laravel/sanctum',
                cookie: {
                    server: true,
                    name: 'XSRF-TOKEN',
                },
                endpoints: {
                    csrf: {url: '/backend/sanctum/csrf-cookie'},
                    login: {url: '/backend/login'},
                    logout: {url: '/backend/logout'},
                    user: {url: '/backend/api/auth/me',}
                },
                user: {
                    property: {
                        client: false,
                        server: false
                    },
                    autoFetch: true
                }
            },
        }
    },
})
```

and this login method:

```
$auth.login({
    body: {
        name: form.value.name,
        email: form.value.email,
        secret: form.value.secret
    }
}).then(() => {
        // ... okay
    })
    .catch((e) => {
        console.log(e)
    });
```

console.log shows 

> TypeError: undefined is not an object (evaluating 'this.http.interceptors')

pointing to

```
    this.http.interceptors.request.eject(this.interceptor);
```

in this context:

```
import { ExpiredAuthSessionError } from "/node_modules/@nuxtjs-alt/auth/dist/runtime/inc/expired-auth-session-error.mjs";
export class RequestHandler {
  constructor(scheme, http) {
    this.scheme = scheme;
    this.http = http;
    this.interceptor = null;
  }
  setHeader(token) {
    if (this.scheme.options.token && this.scheme.options.token.global) {
      this.http.setHeader(this.scheme.options.token.name, token);
    }
  }
  clearHeader() {
    if (this.scheme.options.token && this.scheme.options.token.global) {
      this.http.setHeader(this.scheme.options.token.name, null);
    }
  }
  initializeRequestInterceptor(refreshEndpoint) {
    this.interceptor = this.http.interceptors.request.use(
      async (config) => {
        if (this.scheme.options.token && !this.#needToken(config) || config.url === refreshEndpoint) {
          return config;
        }
        const { valid, tokenExpired, refreshTokenExpired, isRefreshable } = this.scheme.check(true);
        let isValid = valid;
        if (refreshTokenExpired) {
          this.scheme.reset();
          throw new ExpiredAuthSessionError();
        }
        if (tokenExpired) {
          if (!isRefreshable) {
            this.scheme.reset();
            throw new ExpiredAuthSessionError();
          }
          isValid = await this.scheme.refreshController.handleRefresh().then(() => true).catch(() => {
            this.scheme.reset();
            throw new ExpiredAuthSessionError();
          });
        }
        const token = this.scheme.token;
        if (!isValid) {
          if (token && !token.get() && this.#requestHasAuthorizationHeader(config)) {
            throw new ExpiredAuthSessionError();
          }
          return config;
        }
        return this.#getUpdatedRequestConfig(config, token ? token.get() : false);
      }
    );
  }
  reset() {
    this.http.interceptors.request.eject(this.interceptor);
    this.interceptor = null;
  }
  #needToken(config) {
    const options = this.scheme.options;
    return options.token.global || Object.values(options.endpoints).some((endpoint) => typeof endpoint === "object" ? endpoint.url === config.url : endpoint === config.url);
  }
  #getUpdatedRequestConfig(config, token) {
    if (typeof token === "string") {
      config.headers[this.scheme.options.token.name] = token;
    }
    return config;
  }
  #requestHasAuthorizationHeader(config) {
    return !!config.headers[this.scheme.options.token.name];
  }
}
```

in `node_modules/@nuxtjs-alt/auth/dist/runtime/inc/request-handler.mjs`

**Comment by Teranode** [comment]
**Key Changes:**
- The readme specifies that you need to use `@nuxtjs-alt/http` now instead of `@nuxtjs-alt/axios`, it's utilizing ohmyfetch instead of axios.
- The google fonts module has been removed (deprecated in npm) in favor of the official module being nuxt3 compatible so use that instead
- Axios module will still be updated, but will no longer work with the auth module
- (this is old, but) The proxy property has no effect on axios or the http module, you need to explicitly define the proxy module with the `modules` array now (Why?: at some point the nuxt framework will have it own built in proxy (hopefully soon) so i'd be bad to limit choice there)

I've prepared a config file based on what's available with these modules and what you were trying to accomplish in your config
(if you were using `router.middleware` for global middleware utilization, im not sure if that exists, but there is a globalMiddleware option you can enable/disable that ive added for you)

```ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
    modules: [
        '@nuxtjs-alt/auth',
        '@nuxtjs-alt/http',
        '@nuxtjs-alt/proxy',
        '@nuxt/content',
        '@nuxtjs/tailwindcss',
        '@nuxtjs/google-fonts',
        '@intlify/nuxt3',
        '@pinia/nuxt',
    ],
    http: {
        credentials: 'include',
        baseURL: process.env.NUXT_PUBLIC_BASE_URL
    },
    proxy: {
        '/backend': {
            target: process.env.NUXT_PUBLIC_APP_URL,
            changeOrigin: true,
            secure: process.env.NODE_ENV && process.env.NODE_ENV === 'development',
            rewrite: (path) => path.replace(/^\/backend/, ''),
        },
    },
    auth: {
        globalMiddleware: true,
        strategies: {
            laravelSanctum: {
                provider: 'laravel/sanctum',
                cookie: {
                    name: 'XSRF-TOKEN',
                },
                endpoints: {
                    csrf: {
                        url: '/backend/sanctum/csrf-cookie'
                    },
                    login: {
                        url: '/backend/login'
                    },
                    logout: {
                        url: '/backend/logout'
                    },
                    user: {
                        url: '/backend/api/auth/me'
                    }
                }
            },
        }
    },
    build: {
        transpile: [
            '@heroicons/vue',
            /echarts/,
            'resize-detector',
            'reflect-metadata',
            '@headlessui/vue'
        ],
    },
})
```

**Comment by ahoiroman** [comment]
Addition/Question: Would you prefer if I created a new issue for this, @Teranode ?

**Comment by Teranode** [comment]
try doing an npm update and see if it works now
@ahoiroman

**Comment by ahoiroman** [comment]
Hm, I am able to log in, but if I refresh the browser, the user is being logged out again.

**Comment by Teranode** [comment]
2 Questions:

1. did this work for you with axios
2. can you try logging in via firefox? (need to test something)

**Comment by ahoiroman** [comment]
Hi @Teranode ,

sure.

1. Yes
2. Same issue with Firefox. Login works fine, following nuxt-links is fine, refreshing the page leads me back to my login page and the user is no longer logged in

**Comment by Teranode** [comment]
okay run an npm update and try again?

**Comment by ahoiroman** [comment]
Unfortunately it still does not work.

What I did:

1. Removed `package-lock.json`
2. Removed `node_modules`
3. Ran `npm install`
4. Opened a new private tab in firefox
5. Logged in (worked)
6. Refreshed the page (did not work - user is logged out)

But this time there's an error message:

```
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:603:11)
    at Module.sendRedirect (file:///Users/ahoiroman/Entwicklung/nuxtjs/test-website/node_modules/h3/dist/index.mjs:224:13)
    at file:///Users/ahoiroman/Entwicklung/nuxtjs/test-website/.nuxt/dist/server/server.mjs:2006:82
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.callAsync (file:///Users/ahoiroman/Entwicklung/nuxtjs/test-website/node_modules/unctx/dist/index.mjs:46:16)
    at async file:///Users/ahoiroman/Entwicklung/nuxtjs/test-website/.nuxt/dist/server/server.mjs:5996:9 {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

which points to

```
  const encodedLoc = encodeURI(decodeURI(location));
  event.res.statusCode = code;
  event.res.setHeader("Location", encodedLoc);
```

**Comment by Teranode** [comment]
```
  const encodedLoc = encodeURI(decodeURI(location));
  event.res.statusCode = code;
  event.res.setHeader("Location", encodedLoc);
  ```
  what is this from?

**Comment by ahoiroman** [comment]
Does belong to

> declare function sendRedirect(event: CompatibilityEvent, location: string, code?: number): Promise<void>;


This issue seems to happen if `globalMiddleware: true` is declared. If I remove it, another error appears:


```
[nitro] [dev] [uncaughtException] Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.end (node:_http_outgoing:925:15)
    at res.end (file:///Users/ahoiroman/Entwicklung/nuxtjs/test-website/.nuxt/dev/index.mjs:105:10)
    at Immediate.<anonymous> (file:///Users/ahoiroman/Entwicklung/nuxtjs/test-website/node_modules/h3/dist/index.mjs:211:17)
    at process.processImmediate (node:internal/timers:471:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

which points to 


```
function timingMiddleware(_req, res, next) {
  const start = globalTiming.start();
  const _end = res.end;
  res.end = (data, encoding, callback) => {
    const metrics = [["Generate", globalTiming.end(start)], ...globalTiming.metrics];
    const serverTiming = metrics.map((m) => `-;dur=${m[1]};desc="${encodeURIComponent(m[0])}"`).join(", ");
    if (!res.headersSent) {
      res.setHeader("Server-Timing", serverTiming);
    }
    _end.call(res, data, encoding, callback);
  };
  next();
}
```


But I guess it would be better to focus on the first issue first.

**Comment by Teranode** [comment]
im not receiving this error at all

**Comment by ahoiroman** [comment]
Too bad :-( 

I will try to create a reproducing repository.

**Comment by Teranode** [comment]
That would help alot.

**Comment by ahoiroman** [comment]
The logged error is gone after I ran `npm update` again, but the issue with refreshing the page logs out the user is still there.

I am curious how this works "under the hood": If I refresh the page, what is supposed to happen? Is the app supposed to call the `user` endpoint defined in the config in order to fetch the current user data?

```
                endpoints: {
                    csrf: {
                        url: '/backend/sanctum/csrf-cookie'
                    },
                    login: {
                        url: '/backend/login'
                    },
                    logout: {
                        url: '/backend/logout'
                    },
                    user: {
                        url: '/backend/api/auth/me'
                    }
                },
```

**Comment by ahoiroman** [comment]
Alright.

I created a reproducer here: https://github.com/ahoiroman/sanctum-reproducer

I also created a screencast showing that the login itself works but the refresh clears the current user.


https://user-images.githubusercontent.com/23051150/188273368-a250c5ac-abf4-4538-b38e-2a837699b28b.mp4

**Comment by ahoiroman** [comment]
First of all, please don't feel rushed @Teranode. 

But since I can't directly contribute to the solution except for (hopefully) the most accurate error messages possible due to lack of experience with Nuxt, I'd like to help anyway. 

Insofar as the provided repository alone is not enough, I can also recreate the problem on a publicly accessible hosting, so you can use a direct reproducer with Nuxt and a Laravel endpoint.

**Comment by Teranode** [comment]
that would be a great help

**Comment by ahoiroman** [comment]
Alright, so let's do that. In order to send provide access to the servers, please let me know how I can send you sensitive data. 

You may want to register a throw-away-email-address or something like that and post it here.

**Comment by Teranode** [comment]
kq717vwflcx6@explodemail.com

**Comment by ahoiroman** [comment]
Hm, that's strange.

I recreated the situation on a server providing the repositories

- https://github.com/ahoiroman/sanctum-reproducer (Nuxt App)
- https://github.com/ahoiroman/laravel-sanctum-test (Laravel App)

I configured them and the problem did not occur.

Now I wondered whether I may be stupid or not and created a local setup again:

- Created the Laravel App and use Laravel/Valet to create all necessary NGINX configuration
- Created the Nuxt App and used Laravel/Valet to proxy the url to http://127.0.0.1:3000

This is what this looks like

```
valet proxies
+-----------------------+-----+------------------------------------+-----------------------+
| Site                  | SSL | URL                                | Host                  |
+-----------------------+-----+------------------------------------+-----------------------+
| frontend.sanctum-test |  X  | https://frontend.sanctum-test.test | http://127.0.0.1:3000 |
```

```
valet parked
+----------------+-----+----------------------------+---------------------------------------------------+
| Site           | SSL | URL                        | Path                                              |
+----------------+-----+----------------------------+---------------------------------------------------+
| sanctum-test   |     | http://sanctum-test.test   | /Users/ahoiroman/Entwicklung/Laravel/sanctum-test   |
+----------------+-----+----------------------------+---------------------------------------------------+
```

```
valet links
+----------------------+-----+-----------------------------------+-------------------------------------------------+
| Site                 | SSL | URL                               | Path                                            |
+----------------------+-----+-----------------------------------+-------------------------------------------------+
| backend.sanctum-test |  X  | https://backend.sanctum-test.test | /Users/ahoiroman/Entwicklung/Laravel/sanctum-test |
+----------------------+-----+-----------------------------------+-------------------------------------------------+
```

Now this (again) is what is happening:


https://user-images.githubusercontent.com/23051150/188312658-a526ad05-9f95-4d90-adf4-309d24e1c84a.mp4

This is the `.env` of my local Laravel app:

```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:VvN2YSKBctrdqIHEAWsYlcoURsTsQHSHUe1a1Us36Zg=
APP_DEBUG=true
APP_URL=https://backend.sanctum.test.test

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

SESSION_DOMAIN=".sanctum-test.test"
SANCTUM_STATEFUL_DOMAINS=".sanctum-test.test,frontend.sanctum-test.test"

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sanctum-test
DB_USERNAME=root
DB_PASSWORD=
```

I just can't figure out the difference between the local project (which does not work) and the hosted project (which does work with the same repos).

**Comment by ahoiroman** [comment]
Another finding: 

If I refresh the page and try to log in again, Laravel "thinks" that I am already logged in. 

I modified `app/Http/Middleware/RedirectIfAuthenticated.php` slightly to output the login-state of the user:

```
    public function handle(Request $request, Closure $next, ...$guards)
    {
        $guards = empty($guards) ? [null] : $guards;
        ray($request);
        foreach ($guards as $guard) {
            ray(Auth::guard($guard)->check());
            if (Auth::guard($guard)->check()) {
                return redirect(RouteServiceProvider::HOME);
            }
        }

        return $next($request);
    }
```

As you can see in the screencast, the second `ray`-output determining the login state  is `true` after the second login attempt. As far as I understand, this means that Laravel assumes that the user _is_ logged in and tries to redirect to `RouteServiceProvider::HOME`. This would also mean that the provided session information is valid. But still, the user is not logged in in the Nuxt-context.


https://user-images.githubusercontent.com/23051150/188313866-5b374f7d-eaa4-41c0-a5ee-d2f662044532.mp4

**Comment by Teranode** [comment]
try adding: 
```ts
headers: {
    Accept: 'application/json'
},
```

to the endpoints

**Comment by ahoiroman** [comment]
Same error using

```
endpoints: {
    headers: {
        Accept: 'application/json'
    },
    csrf: {
        url: `${process.env.NUXT_PUBLIC_APP_URL}/sanctum/csrf-cookie`
    },
    login: {
        url: `${process.env.NUXT_PUBLIC_APP_URL}/login`
    },
    logout: {
        url: `${process.env.NUXT_PUBLIC_APP_URL}/logout`
    },
    user: {
        url: `${process.env.NUXT_PUBLIC_APP_URL}/api/auth/me`
    }
},
```

**Comment by ahoiroman** [comment]
Hi @Teranode 

I just found out that the working version on the server is triggering this GET-request if I reload the Nuxt-page:


```
193.32.220.xx - - [04/Sep/2022:19:24:33 +0000] "GET /api/auth/me HTTP/1.1" 200 134 "frontend.sanctum-test.dev" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15"
```


This is what I expect: The Nuxt-app "knows" about the user being logged in and fetches the user data.


However on my non-working local setup on my Mac, this call does *not* happen. There is a call on the login, but if I refresh the page, the call to ` /api/auth/me` simply does not happen as I show in this screencast:


https://user-images.githubusercontent.com/23051150/188331208-f6095e71-3d1f-42f4-8f90-9e7570d67700.mp4

**Comment by ahoiroman** [comment]
I was finally able to reproduce the error. It occurs if the domain is a .test-domain.

**Comment by Teranode** [comment]
did you add your domain to the stateful key in the sanctum config?

**Comment by ahoiroman** [comment]
Yes. But even this wouldn’t explain why it works with a .dev domain but not with .test? As you can see in the screencast, the api-call gathering the user information is just not happening.

as I am able to recreate the issue, you may want to see this on the Linux-vps. I already sent a mail regarding the access to the vm, which contains both, nuxt and laravel.

**Comment by ahoiroman** [comment]
I just saw you added the "help wanted" badge. I will do my best ;-) 


I tried to debug the module (well, that's not really debugging - I am console.logging stuff) and found out that this is being called: https://github.com/Teranode/nuxt-module-alternatives/blob/master/%40nuxtjs-alt/auth/src/runtime/schemes/cookie.ts#L166-L169

I console.logged this error like this

```
  async fetchUser(endpoint) {
    console.log("FETCHING USER!");


    if (this.isServerCookie() || this.isClientCookie()) {
      console.log("this.isServerCookie() || this.isClientCookie()")

      if (!this.check().valid) {
        console.log("!this.check().valid")
        return Promise.resolve();
      }
    }
    if (!this.options.endpoints.user) {
      console.log("if (!this.options.endpoints.user)");

      this.$auth.setUser({});
      return Promise.resolve();
    }

    console.log("return this.$auth.requestWith");

    return this.$auth.requestWith(endpoint, this.options.endpoints.user).then((response) => {
      console.log(response)
      let userData;
      if (process.client) {
        userData = getProp(response, this.options.user.property.client);
      } else {
        userData = getProp(response, this.options.user.property.server);
      }
      if (!userData) {
        const error = new Error(`User Data response does not contain field ${this.options.user.property}`);
        return Promise.reject(error);
      }
      this.$auth.setUser(userData);
      return response;
    }).catch((error) => {
      console.log("THERE WAS AN ERROR!!");
      console.log(error)
      this.$auth.callOnError(error, { method: "fetchUser" });
      return Promise.reject(error);
    });
  }

```

 which gave me:


```
FETCHING USER!
this.isServerCookie() || this.isClientCookie()
return this.$auth.requestWith
Strategy api
THERE WAS AN ERROR!!
[FetchError: fetch failed ()]
THERE WAS AN ERROR!!
FetchError: fetch failed ()
    at async Auth.init (/Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/node_modules/@nuxtjs-alt/auth/dist/runtime/core/auth.mjs:63:7)
    at async virtual:nuxt:/Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/.nuxt/auth.plugin.mjs:86:9
    at async Object.callAsync (file:///Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/node_modules/unctx/dist/index.mjs:53:16)
    at async applyPlugin (/Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/node_modules/nuxt/dist/app/nuxt.mjs:74:23)
    at async Module.applyPlugins (/Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/node_modules/nuxt/dist/app/nuxt.mjs:84:5)
    at async createNuxtAppServer (/Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/node_modules/nuxt/dist/app/entry.mjs:30:7)
    at async default (file:///Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:18)
    at async Object.renderToString (file:///Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
    at async file:///Users/ahoiroman/Entwicklung/nuxtjs/sanctum-reproducer/.nuxt/dev/index.mjs:609:21
```

I am not sure how to gather more information about `fetch failed` here.

**Comment by ahoiroman** [comment]
I just added an interceptor to the fetch function:

```
    async request(endpoint, defaults = {}) {
        const handler = this.ctx.$http ? this.ctx.$http : this.ctx.$fetch;
        const request = typeof defaults === "object" ? Object.assign({}, defaults, endpoint) : endpoint;
        const method = request.method ? request.method.toLowerCase() : "get";
        if (request.baseURL === "") {
            request.baseURL = requrl(process.server ? this.ctx.ssrContext?.event.req : "");
        }
        if (!handler) {
            return Promise.reject(new Error("[AUTH] add the @nuxtjs-alt/http module to nuxt.config file"));
        }

        return handler["$" + method](request.url, {
            ...request,
            async onRequestError({options, error}) {
                // Log error
                console.log("LOGGING AN ERROR");
                console.log(request);
                console.log('[fetch request error!]', error)
            }
        }).catch((error) => {
            console.log("ERROR ON FETCHING:", error)
            this.callOnError(error, {method: "request"});
            return Promise.reject(error);
        });
    }
```


This results in 

```
[fetch request error!] TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:6277:34)
    at node:internal/deps/undici/undici:6602:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: InvalidArgumentError: invalid connection header
```

But now I am not sure how to resolve the invalid connection header.

**Comment by Teranode** [comment]
add all of these: 
```ts
'accept',
'cf-connecting-ip',
'cf-ray',
'content-length',
'content-md5',
'content-type',
'host',
'if-modified-since',
'if-none-match',
'x-forwarded-host',
'x-forwarded-port',
'x-forwarded-proto'
```

including the `connection` one and tell me if it's the same

**Comment by ahoiroman** [comment]
Hi @Teranode 

this setup does work as expected:

```
http: {
    credentials: 'include',
    baseURL: process.env.NUXT_PUBLIC_BASE_URL,
    proxyHeadersIgnore: [
        "accept",
        "cf-connecting-ip",
        "cf-ray",
        "content-length",
        "content-md5",
        "content-type",
        "host",
        "if-modified-since",
        "if-none-match",
        "x-forwarded-host",
        "x-forwarded-port",
        "x-forwarded-proto",
        "connection"
    ]
},
```

**Comment by Teranode** [comment]
I've updated the packages

**Comment by ahoiroman** [comment]
I can confirm that this fixes this issue. Thanks a lot!
